### ISSUE TITLE
Heuristic use

### ISSUE THREAD

**Issue by SverreNystad** [SverreNystad/board-master#28]
Our bots can be much better if we implement heuristics to our games

We need a way to deal with creation of these heuristics.
We need to create them our selfs

**Comment by JonBergland** [comment]
<img width="266" alt="Skjermbilde 2024-02-03 210916" src="https://github.com/SverreNystad/board-master/assets/144770553/27b4d633-4ab1-4091-8242-bca15f6b1f87">
The heuristic for Connect 4 is not perfect. When the player had 3 Xs in a row, the iterative deepening agent chose to put its piece on the highlighted square. This resulted in a loss for the agent

**Comment by JonBergland** [comment]
Before:
<img width="353" alt="Skjermbilde 2024-02-05 200144" src="https://github.com/SverreNystad/board-master/assets/144770553/5ba28c04-4ffa-42e6-af99-646cb03c3f79">
After: 
<img width="354" alt="Skjermbilde 2024-02-05 200220" src="https://github.com/SverreNystad/board-master/assets/144770553/18b191d1-7d2a-4da9-9aff-e12d1be79999">

Agent is working as intended now

**Comment by JonBergland** [comment]
The bot now works better if you play with the bot playing first. Still not perfect though:
<img width="308" alt="Skjermbilde 2024-02-06 223820" src="https://github.com/SverreNystad/board-master/assets/144770553/90a59f1f-23bd-47b5-a8f5-7d74b43b5b6f">
